services:
  sqlserver:
    container_name: HRDBContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - sql_vol:/var/opt/mssql
    ports:
      - 1436:1433
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1433"]
      interval: 12s
      retries: 5
    networks:
      app-network:

  hr.app:
    container_name: hrapp
    image: ${DOCKER_REGISTRY-}hrapp
    build:
      context: .
      dockerfile: HR.App/Dockerfile    
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5002:80"
    depends_on:
      - "sqlserver"
    networks:
      app-network:

networks:
  app-network:

volumes:
  sql_vol: